server:
  port: 3081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: admin
        uri: http://localhost:3001/
        predicates:
        - Path=/admin/**
      - id: users
        uri: http://localhost:3002/
        predicates:
        - Path=/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true